POST http://127.0.0.1:8181/accounts
Content-Type: application/json

{
  "accountNumber": "{{accountNumber}}"
}
###
POST http://127.0.0.1:8181/accounts/{{accountNumber}}/deposit
Content-Type: application/json

{
  "amount": {{amount}}
}
###
POST http://127.0.0.1:8181/transactions
Content-Type: application/json

{
  "fromAccountNumber": "tu",
  "toAccountNumber": "vinh",
  "amount": 1000
}
###
GET http://127.0.0.1:8181/accounts
###
GET http://127.0.0.1:8181/transactions/{{accountNumber}}
###