POST http://127.0.0.1:8181/accounts
Content-Type: application/json

{
  "accountNumber": "{{accountNumber}}"
}

###
GET http://127.0.0.1:8181/accounts
###
POST http://127.0.0.1:8181/accounts/{{accountNumber}}/deposit
Content-Type: application/json

{
  "amount": 1000
}
###
GET http://127.0.0.1:8181/transactions/{{accountNumber}}
###