POST http://127.0.0.1:8181/transactions/v1/transfer
Content-Type: application/json

{
  "sendingAccountNumber": "vinh",
  "receivingAccountNumber": "tu",
  "amount": 100
}

###
POST http://127.0.0.1:8181/transactions/v2/transfer
Content-Type: application/json

{
  "sendingAccountNumber": "vinh",
  "receivingAccountNumber": "tu",
  "amount": 1001
}

###
POST http://127.0.0.1:8181/transactions/v2.1/transfer
Content-Type: application/json

{
  "sendingAccountNumber": "vinh",
  "receivingAccountNumber": "tu",
  "amount": 98
}

###
